### PR TITLE
Mainly bug fix for rocci

### PR DESCRIPTION
**Pull request by xianghuzhao**
Most of the changes involve Rocci11.py
1. Password auth should use argument "basic", not "digest"
2. The original method of getting ip is not reliable sometimes. Now use json format to get ip address
3. User could set configuration "flavorName = nouse". Then the VM should use the flavor (cpu, memory) set in the template/image
4. The original uniqueID for rocci is not really unique, because different cloud manager could conflict with each other. Now use the full name as uniqueID, like https://vmdirac03.ihep.ac.cn:11443/compute/745, not only the number 745

### CODE REVIEW

**Comment by xianghuzhao** [comment]
The last new commit fix the bug of list value in the file /root/LocalSiteRequirements. The original line for list value looks like this

```
OwnerGroup = ['production']
```

This will cause mistake while do the match for the JobAgent in the virtual machine. After this fix it will be written in the string format joined by comma

**Comment by xianghuzhao** [comment]
@vmendez 
The client version of rOCCI is 4.2.5, while the server version in IHEP is 1.0.5.
We also have two other OpenNebula server tested. The version in Torino should be also 1.0.5.
The version for the server in JINR is not known.
The previous code using debug mode could work well with IHEP and Torino rOCCI server but get error while connecting with JINR. The output should be different for JINR rOCCI server. So I changed to use json format to get the result and now it works fine with all the 3 rOCCI servers.

This command works fine in our DIRAC server

```
occi --endpoint https://vmdirac03.ihep.ac.cn:11443 --action describe --resource /compute/123 --auth basic --username xxx --password xxx --output-format json_extended
```

**Comment by vmendez** [comment]
@njutiger  @acasajus 
I have check this "occi --action describe compute " is not working for the case "--auth X509".
It is not a good idea to acept a bugfix resolving the case of  "--auth basic" but bugged for the previous X509.
May I sugest you control in the rOCCI driver whether it is selected auth X509 to apply the "occi -d" hack
 or "basic" to apply your patch, please ? 
In this way we will have a valid code both cases (until rOCCI people resolve the bug)
thanks

**Comment by vmendez** [comment]
@njutiger many thanks

My fault, sorry, latest rocci clients are also working for auth X509, @acasajus  we can go on this PR

**Comment by vmendez** [comment]
@acasajus, pull it, please

**Pull request merged**
