### PR TITLE
Autopep8 codebase

### PR DESCRIPTION
**Pull request by alexanderrichards**
* Autopep8 codebase

* Tidying up `CloudEndpoint.py` as @sfayer has some changes that are incoming in another PR. Hope this is ok

### CODE REVIEW

**Comment by andresailer** [comment]
You should use the dirac setup for autopep8: https://github.com/DIRACGrid/DIRAC/blob/integration/setup.cfg

**Comment by alexanderrichards** [comment]
ok I can use autopep8 to essentially do what the first commit does but what about the other two, do you want them?

**Comment by fstagni** [comment]
I added in #116 VMDIRAC checks for Travis, plus the standard configuration files. That should be merge first and then you can autopep8 even every single file.

**Comment by alexanderrichards** [comment]
thanks

**Comment by fstagni** [comment]
Please rebase your changes, I merged #116

**Comment by alexanderrichards** [comment]
ok I've run autopep8 over the whole code base and also fixes the pylint and pycodestyle errors in the `CloudEndpoint.py` file

**Review by fstagni — APPROVED** [review]

**Comment by fstagni** [comment]
Thanks! BTW Travis complains, please fix it: https://travis-ci.org/DIRACGrid/VMDIRAC/jobs/539759200

**Comment by alexanderrichards** [comment]
The failure look like it's coming from a file other than `CloudEndpoint.py` since I only fixed pep8 and pylint violations in this one file it's hardly surprising that other files still have errors in.

**Comment by alexanderrichards** [comment]
I was originally only asked by @sfayer to fix `CloudEndpoint.py` but I've now fixed pycodestyle violations for whole code base. I haven't fixed pylint violations for any other file except `CloudEndpoint.py` as these were not necessary to get the tests passing and I suspect I wouldn't have the time.

**Comment by atsareg** [comment]
Superseded by #117 as autopep8 is done in there

**Pull request closed without merging**
