### PR TITLE
A gConfig.getValue, the way used here cannot not be defined.

### PR DESCRIPTION
**Pull request by sposs**
If a value is set to 0 on purpose, then the removed code makes the agent
fail.

Part of #73 but separated for merging. **This is needed for me to work.**

### CODE REVIEW

**Comment by graciani** [comment]
Since there is a default define the error is wrong. But none if the values
make sense if set to 0. In fact negative values will also produce trouble
down the line. So removing this protection might not be what you want.

Ricardo

-- Sent from my mobile, please excuse typos --

**Comment by sposs** [comment]
This protection was preventing me from setting a parameter to False. This is what I wanted to do, which this fixes. Now this "protection" did not prevent values from being negative...

**Comment by sposs** [comment]
Actually, if one wants the exact check that the value is defiend, one should use getOption, and check for that return value.

**Comment by graciani** [comment]
As I say, what is wrong is the message. And might be the check it self in
some cases.

Ricardo

-- Sent from my mobile, please excuse typos --

**Comment by sposs** [comment]
So what? Is my fix accepted or rejected?

**Comment by graciani** [comment]
If you have no particular problem, can you just change the error message?

Ricardo

On 3 April 2014 12:10, Stephane Poss notifications@github.com wrote:

> So what? Is my fix accepted or rejected?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/pull/78#issuecomment-39434633
> .

## 

# 

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 402 1198

Diagonal, 645
E-08028 Barcelona

#

**Comment by sposs** [comment]
It's not only about the comment, but the checking of the value that's not right. As I said, with the code as it is now, if setting a Value to False or 0, then the code would return a nasty incorrect error.

**Comment by graciani** [comment]
False has no meaning in this context. Since all "defaults" are numeric or
string, the only way to get a "false" is by setting the value to 0 or to an
empty string. In all cases, as far as I can tell, those values make no
sense, since they refer to waiting times and periods.

( "MinWorkingLoad", 0.01, "vmMinWorkingLoad" ),
( "LoadAverageTimespan", 60, "vmLoadAvgTimespan" ),
( "JobWrappersLocation", "/opt/dirac/pro/job/Wrapper/",
"vmJobWrappersLocation" ),
( "HaltPeriod", 1200, "haltPeriod" ),
( "HaltBeforeMargin", 300, "haltBeforeMargin" ),
( "HeartBeatPeriod", 600, "heartBeatPeriod" ),

as you can see it makes no sense that any of them is set to 0.

On 3 April 2014 16:09, Stephane Poss notifications@github.com wrote:

> It's not only about the comment, but the checking of the value that's not
> right. As I said, with the code as it is now, if setting a Value to False
> or 0, then the code would return a nasty incorrect error.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/pull/78#issuecomment-39455062
> .

## 

# 

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 402 1198

Diagonal, 645
E-08028 Barcelona

#

**Comment by sposs** [comment]
Well, that means as soon as someone decides to add something new, that happens to be a bool, then one will have problems. Thus the fix.

**Comment by graciani** [comment]
but removing the fix is not really the best solution, given the current
values.

Ricardo

On 3 April 2014 23:01, Stephane Poss notifications@github.com wrote:

> Well, that means as soon as someone decides to add something new, that
> happens to be a bool, then one will have problems. Thus the fix.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/pull/78#issuecomment-39504345
> .

## 

# 

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 402 1198

Diagonal, 645
E-08028 Barcelona

#

**Comment by sposs** [comment]
What do you mean? I think we don't understand each other. My reason for removing this check is that it's redundant with the checks inside the getValue. Also it forbids certain values that could potentially, in all generality, be used. Please tell me what is wrong with this, and better, tell me what you'd have put?

**Comment by graciani** [comment]
What it is wrong from my point of view is that in the particular place
where the check is done, 0 is in fact a "wrong" value (might be others).

So if you remove this check please add a better check but not simply remove
it. The simpler solution it is the error message is changed to "Wrong Value
for Configuration option XXXX"

Ricardo

On 4 April 2014 09:26, Stephane Poss notifications@github.com wrote:

> What do you mean? I think we don't understand each other. My reason for
> removing this check is that it's redundant with the checks inside the
> getValue. Also it forbids certain values that could potentially, in all
> generality, be used. Please tell me what is wrong with this, and better,
> tell me what you'd have put?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/pull/78#issuecomment-39538330
> .

## 

# 

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 402 1198

Diagonal, 645
E-08028 Barcelona

#

**Comment by sposs** [comment]
and now?

**Comment by graciani** [comment]
Do you think it is acceptable to put back the "old" check but return a more
meaningful error message. You are free to code that negative values also do
not make sense for all those numerical fields.

Regards

Ricardo

On 4 April 2014 12:06, Stephane Poss notifications@github.com wrote:

> and now?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/pull/78#issuecomment-39549623
> .

## 

# 

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 402 1198

Diagonal, 645
E-08028 Barcelona

#

**Comment by sposs** [comment]
No, the old check does not allow for boolean, therefore not acceptable.

**Comment by graciani** [comment]
This is not  general case solution to provide a validity check of the
configuration values. Just minimal consistency check in a very particular
case. If add some poing a boolean is added it will have to be done using a
separated list. In fact I would suggest to separate numerical options and
check that they are positive. And another list for stringd that must be not
null.

Ricardo

-- Sent from my mobile, please excuse typos --

**Comment by sposs** [comment]
So now?

**Pull request merged**
