### PR TITLE
Unused code cleanup

### PR DESCRIPTION
**Pull request by ubeda**
Most of the director modules can be directly deleted, as they are not used ( Amazon, KVM ).

### CODE REVIEW

**Comment by vmendez** [comment]
@ubeda @graciani @acasajus @atsareg 

Amazon and KVM are not fully integrated in v0r7, because currently we don't have a use case to test it, but, please, let then there, it is a point of information for potential users (morever of LHCb case)  and they were used in previous releases. Particulary, there are expression of interest in Amazon, don't avoid potential users !!
The rest of the clean-up is OK for me.

**Comment by acasajus** [comment]
If LHCb doesn't use them it doesn't mean that they are not used, specially
Amazon that will be used by other VOs. It will be worth adapting it to the
new way.

**Comment by ubeda** [comment]
Guys,

  **please read the code**. I've removed all duplicated garbage on the directors, which are just inheriting from the 
  base class. ( Before you were inheriting and re-writing identical methods - aka, copy / paste ). That does not mean
  that I have deleted the Director modules. If you want to keep them, I have no problem with that.

  Talking about directors. I believe the logic applied on VMDIRAC is wrong. I explain myself, there is a director
  "Cloud" that can send jobs to "AmazonImage", "CloudStackImage", "OcciImage" and "NovaImage". 
  This director was ( and still is ) hardcoded on the VirtualMachineScheduler, which means, there is no way you will
  use the KVM and Amazon directors. So, being part of the code or not, ARE NOT USED !. And a simple change 
  at the CS level will not make them being used. This requires deeper changes. 

  Next, what is the purpose of the AmazonDirector if the CloudDirector is instantiating AmazonImages if
  needed ?

  I really believe there are two design patterns being used which are overlapping a bit in the "*Director" business.

  As I said, this PR is not deleting anything that was not duplicated. So, please merge it and we can discuss what 
  goes next.

M.

**Comment by vmendez** [comment]
Amazon will be part of 'Cloud' pool when we get a use case to test it, there are also new features to implement in Amazon. VMDIRAC is for any Virtual Machines, not only Cloud, hypervisors would be another pool, desktop... just to have a high level abstraction of the type of distributed resources. 

AmazonDirector may go to CloudDirector (VMDirector) when we have a use case to test it, we don't implement features without testing environment... and we don't want to delete it, because we are able to provide support for any use case, with a very fast update.

**Comment by acasajus** [comment]
Will not integrate. Superseeded by new commits.

**Pull request closed without merging**
