### PR TITLE
Few minor fixes and unused pieces removed

### PR DESCRIPTION
**Pull request by ubeda**

### CODE REVIEW

**Comment by acasajus** [comment]
Can you please check with @vmendez that the pieces you're cleaning are not used by any other VO?

**Comment by vmendez** [comment]
@ubeda @acasajus 
Thanks Mario.

**Comment by acasajus** [comment]
I'm lost. Is it OK to pull?

**Comment by ubeda** [comment]
From my point of view, you can go ahead.

**Pull request merged**
