### PR TITLE
Merging ubeda VMConfigUpdater with OcciImage and Occi09 using Utilities context & config

### PR DESCRIPTION
**Pull request by vmendez**
I have text new Occiimage and Occi09

Previous PR with new agent WorkloadManagement/VirtualMachineConfigUpdater was with some typos, so it has not been propelly tested before the previous PR. I have correct this typos, but....

Additionally the VirtualMachineConfigUpdater is clearly  not working as expected, it is writing stop_agent file when it is not necessary, furthermore it is very CPU demanding because it is intensive looping which it is not necesary, disabling the VMMonitor stopoing feautures by twist VM CPU load

please, @ubeda, would you debug this agent in a real scenareo ? then submitting a new pull request.
see this VM log's

2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Loading WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Loaded module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Instance path: /opt/dirac 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Control path: /opt/dirac/control/_/_ 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Stop Agent path: /opt/dirac/control/_/_/stop_agent 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ======================================== 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Loaded agent module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Site: Cloud.pic.es 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Setup: VMDIRAC-Production 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Base Module version: 919bc48 (2012-04-19 18:51:40 +0200) Adri Casajs adria@ecm.ub.es  
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Agent version: $Id: $ 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  DIRAC version: v6r7p20 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  DIRAC platform: Linux_x86_64_glibc-2.5 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Polling time: 120 seconds 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Control dir: /opt/dirac/control/WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Work dir: /opt/dirac/work/WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycles: 500 
2013-06-19 10:53:49 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ======================================== 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Starting cycle for module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Remaining 500 of 500 cycles 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: UPDATING  > {'comment': '', 'value': 'v6r7p20', 'key': 'ReleaseVersion', 'levelsBelow': ''} 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/VirtualMachineConfigUpdater/stop_agent 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/JobAgent/stop_agent 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/VirtualMachineMonitorAgent/stop_agent 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Agent module WorkloadManagement/VirtualMachineConfigUpdater run summary 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Executed 1 times previously 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycle took 0.00 seconds 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Average execution time: 0.00 seconds 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Polling time: 120 seconds 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Average execution/polling time: 0.00% 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycle was successful 
2013-06-19 10:53:50 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:55 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Found StopAgent file for agent WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:55 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Stopping agent module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:55 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: No more agent modules to execute. Exiting 
28617: old priority 0, new priority 19
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Loading WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Loaded module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Instance path: /opt/dirac 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Control path: /opt/dirac/control/_/_ 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Stop Agent path: /opt/dirac/control/_/_/stop_agent 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ======================================== 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Loaded agent module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Site: Cloud.pic.es 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Setup: VMDIRAC-Production 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Base Module version: 919bc48 (2012-04-19 18:51:40 +0200) Adri Casajs adria@ecm.ub.es  
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Agent version: $Id: $ 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  DIRAC version: v6r7p20 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  DIRAC platform: Linux_x86_64_glibc-2.5 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Polling time: 120 seconds 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Control dir: /opt/dirac/control/WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Work dir: /opt/dirac/work/WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycles: 500 
2013-06-19 10:53:58 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ======================================== 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Starting cycle for module WorkloadManagement/VirtualMachineConfigUpdater 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Remaining 500 of 500 cycles 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: UPDATING  > {'comment': '', 'value': '', 'key': 'ReleaseVersion', 'levelsBelow': ''} 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/VirtualMachineConfigUpdater/stop_agent 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/JobAgent/stop_agent 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater   INFO: Written stop_agent in: /opt/dirac/control/WorkloadManagement/VirtualMachineMonitorAgent/stop_agent 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: ---------------------------------------- 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE: Agent module WorkloadManagement/VirtualMachineConfigUpdater run summary 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Executed 1 times previously 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycle took 0.00 seconds 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Average execution time: 0.00 seconds 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Polling time: 120 seconds 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Average execution/polling time: 0.00% 
2013-06-19 10:53:59 UTC WorkloadManagement/VirtualMachineConfigUpdater NOTICE:  Cycle was successful

### CODE REVIEW

**Comment by ubeda** [comment]
One bug was introduced adding Ricardo's suggestion ( which yes, I did not test as I assume it was correct ). 

Regarding the CPU: if you running with the default polling time, any agent can become CPU consuming.

Quoting your own words: "would you debug this agent in a real scenareo ?" I assume your CS without Pilot/Version is a good example of it.

Nevertheless, I agree, the agent was not correct.

**Comment by ubeda** [comment]
I have another little comment, regarding NovaConfiguration. 
If you write:

```
config[ 'user' ]                    = self.__user
config[ 'password' ]                = self.__password
```

when the configuration is validated they are printed on the logs. However, removing those two lines prevents them from being printed them and the functionality remains intact as they are accessed using 

```
authConfig( ... )
```

**Comment by vmendez** [comment]
About autConfig(), this is my log:
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: user : ********\* 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: imageDriver : qcow2-one-3.2.1 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: occiURI : http://one01.pic.es:4569 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: password : ********\* 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: dns1 : 193.109.175.5 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: vmPolicy : elastic 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: User and Password are NOT printed. 
2013-06-19 10:10:46 UTC WorkloadManagement/VirtualMachineScheduler/OcciConfiguration   INFO: *************************************************\* 

As you can see I neither print them, your authConfig is much more elegant, of course

**Comment by vmendez** [comment]
About  <<Quoting your own words: "would you debug this agent in a real scenareo ?" I assume your CS without Pilot/Version is a good example of it>>
your assumption is erroneous, the problem is 
if pilotVersion > releaseVersion:
They are not numbers !!!

Please @ubeda, don't "despejar balones fuera" , don't do PR without testing is a golden rule in DIRAC core.

**Comment by graciani** [comment]
Some further comments on VirtualMachineConfigUpdater.py:
- better use "self.am_getStopAgentFile()" to get the location if the control file. If the logic ever get changed your code will continue to work. Substitute some of the levels by "*" to do the glob search.
- if this agent should run on a local installation mode, the update of the ReleaseVersion should be done when the installation is updated, if is running with some CVMFS like installation you will need to tell it which cfg file is to be updated. Who is taking care of the real update? changing the configuration will make the Matcher happy, but ....
- Pilot/Version should be read as a list of strings, and you need to update if your current version is not in the list, to the newest version in the list.
- You will also need to take care of the Pilot/Project  that is to be published under ReleaseProject (similar to the above) if not DIRAC, 
- localCFG should be read using getValue() with a proper default (like gConfig) to avoid unexpected returned values.
- direct alphabetic string comparison does not work with dirac versions

If anything fails in the update of the configuration (or in the subsequent restart reading the new values) you may end in a infinite loop (the agent exits immediately and executes again). You should probably keep running the same agent (not updating to the new version) until the configured maximum number of iterations has arrived. Only the rest of the Agents should be restarted. But you should be able to determine the version that the other agents are loading when they restart. Maybe reading it from the configuration file that you are suppose to update.

**Comment by ubeda** [comment]
@vmendez 
pilotVersion > releaseVersion, if they are strings this still works. I'm not going to discuss how python works.

```
'b' > 'a' 
True
```

EDIT: I did not understand your point until I read Ricardo's comment.

However, @graciani is right, they can be lists ( the thing is that is not the case in LHCb and I did not consider it ). From your logs I see "UPDATING >..." where is should see "UPDATING 'PilotVersion'> ..." ( the ... was a bug on my side ) which means it is not reading from the CS the Pilot/Version.

@vmendez, "don't do PR without testing is a golden rule in DIRAC core" I completely agree. Just to remind you to check the following files as well. Please, **stop with this**.
- CloudStackImage.py
- OutputDataExecutor.py
- AmazonImage.py
- CloudStackInstance.py

**Comment by ubeda** [comment]
Your points @graciani:

a) agree ( EDIT: done )
b) EDIT: agree. I'd say, it the local installation needs to be redone, probably is worth killing the VM and booting fresh one. "Who is taking care of the real update?" the agent.run ( at least with the LHCb context scripts )
c) agree ( EDIT: done )
d) is it foreseen that a VM changes Project ??
e) I do not see any getValue on the CFG class.
f) I just realized that 'v7r11p1' > 'v7r1p1' is False @vmendez ( EDIT: done )

From your last comment, I see a corner case: what if is this particular agent is the one that needs to be rebooted ? Will have to wait a bit..

**Comment by ubeda** [comment]
Just to conclude. 

I think I've addressed most of your suggestions / issues on the [PR47](https://github.com/DIRACGrid/VMDIRAC/pull/47). In order to not pollute this PR with PR47 comments, I suggest to continue them on the link above.

**Pull request closed without merging**
